name: 'Helm: setup'
description: 'Setup Helm on action runner'
inputs:
  version:  
    description: 'The desired helm version'
    required: true
    default: 'v4.0.5'
outputs: {}
runs:
  using: 'composite'
  steps:
    ## perform helm installation
    - name: Install Helm
      uses: azure/setup-helm@v4.3.0
      with:
        version: ${{ inputs.version }}
