on: [push]

jobs:
  integration:
    runs-on: ubuntu-latest
    name: 'Integration'
    steps:
      - name: "Checkout"
        uses: cx-marcelo-pereira/actions/git-checkout@main
      - name: "Helm setup"
        uses: cx-marcelo-pereira/actions/helm-setup@main
        with:
          version: 'v4.0.4'